import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col  ">
          <div className="flex flex-row align-center justify-between h-16 items-center">
            <div>MAPZ</div>
            <div>MENU GUEST</div>
          </div>
          <div className="flex flex-grow">{children}</div>
        </main>
      </body>
    </html>
  );
}
