import { AuthButton } from "@/components/AuthButton";
import { FiltersButton } from "@/components/FiltersButton";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col  ">
          <NextAuthProvider>
            <div className="flex p-2 flex-row align-center justify-between h-16 items-center">
              <div className="flex flex-row align-center justify-between items-center">
                <img src="logo.png" className="mr-2" />
                <span className=" text-2xl font-bold ">Mapz</span>
              </div>
              <FiltersButton />
              <AuthButton />
            </div>
            <div className="flex flex-grow">{children}</div>
          </NextAuthProvider>
        </main>
      </body>
    </html>
  );
}
